services:
  postgres-dev:
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    networks: [ net-bnv-manager ]
    volumes:
      - postgres-vol:/var/lib/postgresql/data/
    env_file: [ .env ]
    image: bnv-manager-v2-dev/postgres:${DEV_TAG}
    build:
      dockerfile: ./build/dockerfiles/postgres.Dockerfile

  frontend-dev:
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    env_file: [ .env ]
    networks: [ net-bnv-manager ]
    user: "${UID}:${GID}"
    image: bnv-manager-v2-dev/frontend:${DEV_TAG}
    build:
      dockerfile: ./build/dockerfiles/frontend-dev.Dockerfile

  jaeger-dev:
    restart: unless-stopped
    env_file: [ .env ]
    networks: [ net-bnv-manager ]
    ports:
      - "127.0.0.1:16686:16686"
    image: bnv-manager-v2-dev/jaeger:${DEV_TAG}
    build:
      dockerfile: build/dockerfiles/jaeger-dev.Dockerfile

  webserver-dev:
    labels:
      - webserver
    restart: unless-stopped
    depends_on: [ postgres-dev ]
    networks: [ net-bnv-manager ]
    stop_signal: SIGTERM
    volumes:
      - bnv-manager-vol:/var/lib/bnv-manager
      - ./webserver/migrations:/migrations
    env_file: [ .env ]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-dev:4317
      - RUST_LOG=${RUST_LOG-info,webserver=debug}
      - POSTGRES_HOST=postgres-dev
    user: "${UID}:${GID}"
    image: bnv-manager-v2-dev/webserver-dev:${DEV_TAG}
    build:
      dockerfile: ./build/dockerfiles/bnv-manager-dev.Dockerfile

  nginx-dev:
    restart: unless-stopped
    networks: [ net-bnv-manager ]
    ports:
      - "8080:80"
    depends_on: [ webserver-dev, frontend-dev, jaeger-dev ]
    env_file: [ .env ]
    volumes:
      - ./data/conf/nginx-dev/bnv-manager.conf:/etc/nginx/conf.d/default.conf
    image: bnv-manager-v2-dev/nginx:${DEV_TAG}
    build:
      dockerfile: ./build/dockerfiles/nginx-dev.Dockerfile

networks:
  net-bnv-manager:
    driver: bridge

volumes:
  postgres-vol:
    name: ${COMPOSE_PROJECT_NAME}-postgres-vol-${DEV_TAG}
  bnv-manager-vol:
